name: Renovate
on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: write  

jobs:
  renovate:
    name: Run self-hosted Renovate
    runs-on: ubuntu-24.04
    steps:

      - name: Login to registry.redhat.io
        uses: docker/login-action@343f7c4344506bcbf9b4de18042ae17996df046d #v3.0.0
        with:
          registry: registry.redhat.io
          username: ${{ secrets.RH_REGISTRY_USERNAME }}
          password: ${{ secrets.RH_REGISTRY_PASSWORD }}
            
      # renovate clones the repository again in its container fs but it needs
      # the renovate configuration to start.
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Self-hosted Renovate
        uses: renovatebot/github-action@c21017a4a2fc9f42953bcc907e375a5a544557ec # v41.0.18
        env:
          # default to DEBUG log level, this is always useful
          LOG_LEVEL: 'DEBUG'
          RH_REGISTRY_USERNAME: ${{ secrets.RH_REGISTRY_USERNAME }}
          RH_REGISTRY_PASSWORD: ${{ secrets.RH_REGISTRY_PASSWORD }}
        with:
          # renovate: datasource=github-releases depName=renovatebot/renovate
          renovate-version: 39.207.3
          docker-cmd-file: .github/renovate-entrypoint.sh
          docker-user: root
          configurationFile: .github/renovate-config.js
          token: '${{ secrets.RENOVATE_TOKEN }}'
          env-regex: '^(?:RENOVATE_\w+|RH_REGISTRY_USERNAME|RH_REGISTRY_PASSWORD|LOG_LEVEL)$'
          mount-docker-socket: true
